name: Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 300
                    pm2 stop site1
                    cd $SITE_WORKDIR/site1
                    npm run build
                    pm2 start site1
                    sleep 10
                    pm2 stop site2
                    cd $SITE_WORKDIR/site2
                    npm run build
                    pm2 start site2
