name: Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Rebuild
    runs-on: ubuntu-latest
    steps:
    - name: Failover to Site2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 300
                    sudo /usr/bin/sed -i 's|root /home/cnid/cryptonodeid/site1/dist;|root /home/cnid/cryptonodeid/site2/dist;|g' /etc/nginx/sites-available/cryptonodeid
                    sudo /usr/bin/systemctl reload nginx.service
    - name: Rebuild Site1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    cd ~/cryptonodeid/site1
                    git pull
                    npm run build
    - name: Failback LB Site1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    sudo /usr/bin/sed -i 's|root /home/cnid/cryptonodeid/site2/dist;|root /home/cnid/cryptonodeid/site1/dist;|g' /etc/nginx/sites-available/cryptonodeid
                    sudo /usr/bin/systemctl reload nginx.service
    - name: Rebuild Site2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    cd ~/cryptonodeid/site2
                    git pull
                    npm run build
