name: Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Rebuild
    runs-on: ubuntu-latest
    steps:
    - name: Down LB Site1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDLB }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 300
                    sudo /usr/bin/sed -i 's/server websrv.cnid:58898 fail_timeout=2s max_fails=2;/server websrv.cnid:58898 fail_timeout=2s max_fails=2 down;/g' /etc/nginx/sites-available/cryptonodeid.conf
                    sudo /usr/bin/systemctl reload nginx.service
    - name: Rebuild Site1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    cd $SITE_WORKDIR/site1
                    npm run build
    - name: Up LB Site1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDLB }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    sudo /usr/bin/sed -i 's/server websrv.cnid:58898 fail_timeout=2s max_fails=2 down;/server websrv.cnid:58898 fail_timeout=2s max_fails=2;/g' /etc/nginx/sites-available/cryptonodeid.conf
                    sudo /usr/bin/systemctl reload nginx.service
    - name: Down LB Site2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDLB }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    sudo /usr/bin/sed -i 's/server websrv.cnid:58899 fail_timeout=2s max_fails=2;/server websrv.cnid:58899 fail_timeout=2s max_fails=2 down;/g' /etc/nginx/sites-available/cryptonodeid.conf
                    sudo /usr/bin/systemctl reload nginx.service
    - name: Rebuild Site2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    cd $SITE_WORKDIR/site2
                    npm run build    
    - name: Up LB Site2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDLB }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    sleep 10
                    sudo /usr/bin/sed -i 's/server websrv.cnid:58899 fail_timeout=2s max_fails=2 down;/server websrv.cnid:58899 fail_timeout=2s max_fails=2;/g' /etc/nginx/sites-available/cryptonodeid.conf
                    sudo /usr/bin/systemctl reload nginx.service
