name: Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GHCNIDHOST }}
        username: ${{ secrets.GHCNIDUSER }}
        key: ${{ secrets.GHCNIDSSHPK }}
        script: |
                    bash ~/cryptonodeid/rebuild.sh
