name: Rebuild
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      env:
        WORKDIR: ${{ secrets.GHCNIDWS-github_cnid_ssh }}
      with:
        host: ${{ secrets.GHCNIDHOST-github_cnid_ssh }}
        username: ${{ secrets.GHCNIDUSER-github_cnid_ssh }}
        key: ${{ secrets.GHCNIDSSHPK-github_cnid_ssh }}
        script: |
                    sleep 300
                    pm2 stop site1
                    cd $WORKDIR/site1
                    npm run build
                    pm2 start site1
                    sleep 10
                    pm2 stop site2
                    cd $WORKDIR/site2
                    npm run build
                    pm2 start site2
